export const menuCategories = [
  "All",
  "Coffee",
  "Espresso",
  "Cold Coffee",
  "Desserts",
  "Breakfast",
  "Snacks",
] as const;

export const menuData = [
  {
    category: "Coffee",
    name: "Classic Americano",
    description: "Rich espresso with hot water",
    price: "$4.50",
    image: "https://images.unsplash.com/photo-1712000155326-708e81be975e?w=600",
    alt: "Classic Americano served at Maati Art Cafe",
  },
  {
    category: "Coffee",
    name: "Cappuccino",
    description: "Espresso with steamed milk foam",
    price: "$5.00",
    image: "https://images.unsplash.com/photo-1633677224449-7787d6ed2985?w=600",
    alt: "Cappuccino with milk foam at Maati Art Cafe",
  },
  {
    category: "Coffee",
    name: "Flat White",
    description: "Smooth microfoam over espresso",
    price: "$5.50",
    image: "https://images.unsplash.com/photo-1658933933131-c4ff2aabc70d?w=600",
    alt: "Flat white coffee in a ceramic cup",
  },
  {
    category: "Espresso",
    name: "Double Espresso",
    description: "Bold and intense",
    price: "$3.50",
    image: "https://images.unsplash.com/photo-1762657433581-15773c721a42?w=600",
    alt: "Double espresso shot prepared by Maati Art Cafe",
  },
  {
    category: "Espresso",
    name: "Macchiato",
    description: "Espresso with a dollop of foam",
    price: "$4.00",
    image: "https://images.unsplash.com/photo-1764361276489-79b17d9a8782?w=600",
    alt: "Macchiato topped with foam at Maati Art Cafe",
  },
  {
    category: "Cold Coffee",
    name: "Iced Latte",
    description: "Smooth cold brew with milk",
    price: "$5.50",
    image: "https://images.unsplash.com/photo-1769138885124-9d9e52bb3c8a?w=600",
    alt: "Iced latte with layered milk and espresso",
  },
  {
    category: "Cold Coffee",
    name: "Cold Brew",
    description: "24-hour steeped perfection",
    price: "$5.00",
    image: "https://images.unsplash.com/photo-1665119497036-496bcf37425b?w=600",
    alt: "Cold brew coffee served over ice",
  },
  {
    category: "Cold Coffee",
    name: "Nitro Cold Brew",
    description: "Smooth, creamy, cascading",
    price: "$6.00",
    image: "https://images.unsplash.com/photo-1769970630294-924a48b99cb0?w=600",
    alt: "Nitro cold brew in a tall glass",
  },
  {
    category: "Desserts",
    name: "Chocolate Cake",
    description: "Rich dark chocolate layers",
    price: "$7.00",
    image: "https://images.unsplash.com/photo-1761637604549-4943604df127?w=600",
    alt: "Chocolate cake slice on a ceramic plate",
  },
  {
    category: "Desserts",
    name: "Strawberry Shortcake",
    description: "Fresh berries and cream",
    price: "$6.50",
    image: "https://images.unsplash.com/photo-1774689407321-7b0ff1c77f85?w=600",
    alt: "Strawberry shortcake with fresh cream",
  },
  {
    category: "Desserts",
    name: "Tiramisu",
    description: "Classic Italian dessert",
    price: "$7.50",
    image: "https://images.unsplash.com/photo-1761637604893-f049f46d2bcd?w=600",
    alt: "Tiramisu dessert served at Maati Art Cafe",
  },
  {
    category: "Desserts",
    name: "Cheesecake",
    description: "New York style perfection",
    price: "$6.00",
    image: "https://images.unsplash.com/photo-1764445415300-0e07729dfc4a?w=600",
    alt: "New York style cheesecake at Maati Art Cafe",
  },
  {
    category: "Breakfast",
    name: "Croissant",
    description: "Buttery, flaky, French",
    price: "$4.50",
    image: "https://images.unsplash.com/photo-1762922425248-2ef724c3ceb0?w=600",
    alt: "Freshly baked croissant from Maati Art Cafe",
  },
  {
    category: "Breakfast",
    name: "Avocado Toast",
    description: "Sourdough with fresh avocado",
    price: "$9.00",
    image: "https://images.unsplash.com/photo-1773399159452-0b9b205c751f?w=600",
    alt: "Avocado toast served for breakfast at Maati Art Cafe",
  },
  {
    category: "Breakfast",
    name: "Bagel & Lox",
    description: "Smoked salmon on fresh bagel",
    price: "$10.00",
    image: "https://images.unsplash.com/photo-1774988861608-0c46bbee0dfb?w=600",
    alt: "Bagel with smoked salmon and lox",
  },
  {
    category: "Snacks",
    name: "Muffins",
    description: "Blueberry or chocolate chip",
    price: "$3.50",
    image: "https://images.unsplash.com/photo-1771069838532-0b72cd163ae1?w=600",
    alt: "Fresh muffins displayed at Maati Art Cafe",
  },
  {
    category: "Snacks",
    name: "Cookies",
    description: "Freshly baked daily",
    price: "$2.50",
    image: "https://images.unsplash.com/photo-1762267660021-8f501db38ee1?w=600",
    alt: "Freshly baked cookies at Maati Art Cafe",
  },
] as const;
